### PR TITLE
ISSUE-33 Add compatibility with gradle 2.14

### PR DESCRIPTION
**Pull request by sparkym3**
I have bumped the release version to 2.0 since it breaks everything beyond gradle 2.14

### CODE REVIEW

**Comment by barnhill** [comment]
👍   This should fix exactly what we were running into when trying to upgrade to 2.14.

**Comment by dcendents** [comment]
Thanks but I'm trying to keep the plugin source as close to the original maven plugin from gradle.
Your pull request modifies too many things and diverges too much.

I've release version 1.4 of the plugin to be used by gradle 2.14, so please give it a go.

Thanks for the PR though, I appreciate your commitment.

**Comment by sparkym3** [comment]
No Problem, I appreciate you being on top of it and getting an acceptable solution pulled in.

**Comment by barnhill** [comment]
agreed ... good job dcendents

**Pull request closed without merging**
